name: Push terraform image

on:   
  push:
    branches:
      - master
    paths:
      - 'terraform/Dockerfile'
      - '.github/workflows/terraform.yaml'

env:
  REGISTRY: "ghcr.io/msaitz"
  IMAGE_NAME: "terraform"
  IMAGE_VERSION: "1.0.2"
  
jobs:
  build-and-push-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: terraform/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
