name: Push terraform image

on:
  pull_request:
    paths:
      - 'terraform/Dockerfile'
      - '.github/workflows/terraform-beta.yaml'

env:
  REGISTRY: "ghcr.io/msaitz"
  IMAGE_NAME: "terraform"
  IMAGE_VERSION: "beta"

jobs:
  push-beta:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file ${IMAGE_NAME}/Dockerfile --tag ${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION} --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}
